{% set name = "libusb1" %}
{% set version = "3.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/libusb1-{{ version }}.tar.gz
  sha256: a11a6095e718cd49418a96329314da271cca6be7b4317a142724523371ac8961

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - python >=3.4

test:
  imports:
    - usb1
    - usb1.__pyinstaller
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/vpelletier/python-libusb1
  summary: Pure-python wrapper for libusb-1.0
  license: LGPL-2.1-or-later
  license_file: COPYING.LESSER

extra:
  recipe-maintainers:
    - ickc
